[{
	'name': 'Admin Menu'
	'icons': [{
		'code': 'f333',
		'class': 'dashicons-menu',
		'name': 'menu',
		'synonyms': '',
	}, {
		'code': 'f319',
		'class': 'dashicons-admin-site',
		'name': 'site',
		'synonyms': '',
	}, {
		'code': 'f226',
		'class': 'dashicons-dashboard',
		'name': 'dashboard',
		'synonyms': '',
	}, {
		'code': 'f109',
		'class': 'dashicons-admin-post',
		'name': 'post',
		'synonyms': '',
	}, {
		'code': 'f104',
		'class': 'dashicons-admin-media',
		'name': 'media',
		'synonyms': '',
	}, {
		'code': 'f103',
		'class': 'dashicons-admin-links',
		'name': 'links',
		'synonyms': '',
	}, {
		'code': 'f105',
		'class': 'dashicons-admin-page',
		'name': 'page',
		'synonyms': '',
	}, {
		'code': 'f101',
		'class': 'dashicons-admin-comments',
		'name': 'comments',
		'synonyms': '',
	}, {
		'code': 'f100',
		'class': 'dashicons-admin-appearance',
		'name': 'appearance',
		'synonyms': '',
	}, {
		'code': 'f106',
		'class': 'dashicons-admin-plugins',
		'name': 'plugins',
		'synonyms': '',
	}, {
		'code': 'f110',
		'class': 'dashicons-admin-users',
		'name': 'users',
		'synonyms': '',
	}, {
		'code': 'f107',
		'class': 'dashicons-admin-tools',
		'name': 'tools',
		'synonyms': '',
	}, {
		'code': 'f108',
		'class': 'dashicons-admin-settings',
		'name': 'settings',
		'synonyms': '',
	}, {
		'code': 'f112',
		'class': 'dashicons-admin-network',
		'name': 'network',
		'synonyms': '',
	}, {
		'code': 'f102',
		'class': 'dashicons-admin-home',
		'name': 'home',
		'synonyms': '',
	}, {
		'code': 'f111',
		'class': 'dashicons-admin-generic',
		'name': 'generic',
		'synonyms': '',
	}, {
		'code': 'f148',
		'class': 'dashicons-admin-collapse',
		'name': 'collapse',
		'synonyms': '',
	}, {
		'code': 'f536',
		'class': 'dashicons-filter',
		'name': 'filter',
		'synonyms': '',
	}, {
		'code': 'f540',
		'class': 'dashicons-admin-customizer',
		'name': 'customizer',
		'synonyms': '',
	}, {
		'code': 'f541',
		'class': 'dashicons-admin-multisite',
		'name': 'multisite',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Welcome Screen'
	'icons': [{
		'code': 'f119',
		'class': 'dashicons-welcome-write-blog',
		'name': 'write blog',
		'synonyms': '',
	}, {
		'code': 'f119',
		'class': 'dashicons-welcome-edit-page',
		'name': '',
		'synonyms': '',
	}, {
		'code': 'f133',
		'class': 'dashicons-welcome-add-page',
		'name': 'add page',
		'synonyms': '',
	}, {
		'code': 'f115',
		'class': 'dashicons-welcome-view-site',
		'name': 'view site',
		'synonyms': '',
	}, {
		'code': 'f116',
		'class': 'dashicons-welcome-widgets-menus',
		'name': 'widgets and menus',
		'synonyms': '',
	}, {
		'code': 'f117',
		'class': 'dashicons-welcome-comments',
		'name': 'comments',
		'synonyms': '',
	}, {
		'code': 'f118',
		'class': 'dashicons-welcome-learn-more',
		'name': 'learn more',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Post Formats'
	'icons': [{
		'code': 'f109',
		'class': 'dashicons-format-standard',
		'name': '',
		'synonyms': '',
	}, {
		'code': 'f123',
		'class': 'dashicons-format-aside',
		'name': 'aside',
		'synonyms': '',
	}, {
		'code': 'f128',
		'class': 'dashicons-format-image',
		'name': 'image',
		'synonyms': '',
	}, {
		'code': 'f161',
		'class': 'dashicons-format-gallery',
		'name': 'gallery',
		'synonyms': '',
	}, {
		'code': 'f126',
		'class': 'dashicons-format-video',
		'name': 'video',
		'synonyms': '',
	}, {
		'code': 'f130',
		'class': 'dashicons-format-status',
		'name': 'status',
		'synonyms': '',
	}, {
		'code': 'f122',
		'class': 'dashicons-format-quote',
		'name': 'quote',
		'synonyms': '',
	}, {
		'code': 'f103',
		'class': 'dashicons-format-links',
		'name': 'links',
		'synonyms': '',
	}, {
		'code': 'f125',
		'class': 'dashicons-format-chat',
		'name': 'chat',
		'synonyms': '',
	}, {
		'code': 'f127',
		'class': 'dashicons-format-audio',
		'name': 'audio',
		'synonyms': '',
	}, {
		'code': 'f306',
		'class': 'dashicons-camera',
		'name': 'camera',
		'synonyms': '',
	}, {
		'code': 'f232',
		'class': 'dashicons-images-alt',
		'name': 'images (alt)',
		'synonyms': '',
	}, {
		'code': 'f233',
		'class': 'dashicons-images-alt2',
		'name': 'images (alt 2)',
		'synonyms': '',
	}, {
		'code': 'f234',
		'class': 'dashicons-video-alt',
		'name': 'video (alt)',
		'synonyms': '',
	}, {
		'code': 'f235',
		'class': 'dashicons-video-alt2',
		'name': 'video (alt 2)',
		'synonyms': '',
	}, {
		'code': 'f236',
		'class': 'dashicons-video-alt3',
		'name': 'video (alt 3)',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Media'
	'icons': [{
		'code': 'f501',
		'class': 'dashicons-media-archive',
		'name': 'archive',
		'synonyms': '',
	}, {
		'code': 'f500',
		'class': 'dashicons-media-audio',
		'name': 'audio',
		'synonyms': '',
	}, {
		'code': 'f499',
		'class': 'dashicons-media-code',
		'name': 'code',
		'synonyms': '',
	}, {
		'code': 'f498',
		'class': 'dashicons-media-default',
		'name': 'default',
		'synonyms': '',
	}, {
		'code': 'f497',
		'class': 'dashicons-media-document',
		'name': 'document',
		'synonyms': '',
	}, {
		'code': 'f496',
		'class': 'dashicons-media-interactive',
		'name': 'interactive',
		'synonyms': '',
	}, {
		'code': 'f495',
		'class': 'dashicons-media-spreadsheet',
		'name': 'spreadsheet',
		'synonyms': '',
	}, {
		'code': 'f491',
		'class': 'dashicons-media-text',
		'name': 'text',
		'synonyms': '',
	}, {
		'code': 'f490',
		'class': 'dashicons-media-video',
		'name': 'video',
		'synonyms': '',
	}, {
		'code': 'f492',
		'class': 'dashicons-playlist-audio',
		'name': 'audio playlist',
		'synonyms': '',
	}, {
		'code': 'f493',
		'class': 'dashicons-playlist-video',
		'name': 'video playlist',
		'synonyms': '',
	}, {
		'code': 'f522',
		'class': 'dashicons-controls-play',
		'name': 'play player',
		'synonyms': '',
	}, {
		'code': 'f523',
		'class': 'dashicons-controls-pause',
		'name': 'player pause',
		'synonyms': '',
	}, {
		'code': 'f519',
		'class': 'dashicons-controls-forward',
		'name': 'player forward',
		'synonyms': '',
	}, {
		'code': 'f517',
		'class': 'dashicons-controls-skipforward',
		'name': 'player skip forward',
		'synonyms': '',
	}, {
		'code': 'f518',
		'class': 'dashicons-controls-back',
		'name': 'player back',
		'synonyms': '',
	}, {
		'code': 'f516',
		'class': 'dashicons-controls-skipback',
		'name': 'player skip back',
		'synonyms': '',
	}, {
		'code': 'f515',
		'class': 'dashicons-controls-repeat',
		'name': 'player repeat',
		'synonyms': '',
	}, {
		'code': 'f521',
		'class': 'dashicons-controls-volumeon',
		'name': 'player volume on',
		'synonyms': '',
	}, {
		'code': 'f520',
		'class': 'dashicons-controls-volumeoff',
		'name': 'player volume off',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Image Editing'
	'icons': [{
		'code': 'f165',
		'class': 'dashicons-image-crop',
		'name': 'crop',
		'synonyms': '',
	}, {
		'code': 'f531',
		'class': 'dashicons-image-rotate',
		'name': 'rotate',
		'synonyms': '',
	}, {
		'code': 'f166',
		'class': 'dashicons-image-rotate-left',
		'name': 'rotate left',
		'synonyms': '',
	}, {
		'code': 'f167',
		'class': 'dashicons-image-rotate-right',
		'name': 'rotate right',
		'synonyms': '',
	}, {
		'code': 'f168',
		'class': 'dashicons-image-flip-vertical',
		'name': 'flip vertical',
		'synonyms': '',
	}, {
		'code': 'f169',
		'class': 'dashicons-image-flip-horizontal',
		'name': 'flip horizontal',
		'synonyms': '',
	}, {
		'code': 'f533',
		'class': 'dashicons-image-filter',
		'name': 'filter',
		'synonyms': '',
	}, {
		'code': 'f171',
		'class': 'dashicons-undo',
		'name': 'undo',
		'synonyms': '',
	}, {
		'code': 'f172',
		'class': 'dashicons-redo',
		'name': 'redo',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'TinyMCE'
	'icons': [{
		'code': 'f200',
		'class': 'dashicons-editor-bold',
		'name': 'bold',
		'synonyms': '',
	}, {
		'code': 'f201',
		'class': 'dashicons-editor-italic',
		'name': 'italic',
		'synonyms': '',
	}, {
		'code': 'f203',
		'class': 'dashicons-editor-ul',
		'name': 'ul',
		'synonyms': '',
	}, {
		'code': 'f204',
		'class': 'dashicons-editor-ol',
		'name': 'ol',
		'synonyms': '',
	}, {
		'code': 'f205',
		'class': 'dashicons-editor-quote',
		'name': 'quote',
		'synonyms': '',
	}, {
		'code': 'f206',
		'class': 'dashicons-editor-alignleft',
		'name': 'alignleft',
		'synonyms': '',
	}, {
		'code': 'f207',
		'class': 'dashicons-editor-aligncenter',
		'name': 'aligncenter',
		'synonyms': '',
	}, {
		'code': 'f208',
		'class': 'dashicons-editor-alignright',
		'name': 'alignright',
		'synonyms': '',
	}, {
		'code': 'f209',
		'class': 'dashicons-editor-insertmore',
		'name': 'insertmore',
		'synonyms': '',
	}, {
		'code': 'f210',
		'class': 'dashicons-editor-spellcheck',
		'name': 'spellcheck',
		'synonyms': '',
	}, {
		'code': 'f211',
		'class': 'dashicons-editor-distractionfree',
		'name': '',
		'synonyms': '',
	}, {
		'code': 'f211',
		'class': 'dashicons-editor-expand',
		'name': 'expand',
		'synonyms': '',
	}, {
		'code': 'f506',
		'class': 'dashicons-editor-contract',
		'name': 'contract',
		'synonyms': '',
	}, {
		'code': 'f212',
		'class': 'dashicons-editor-kitchensink',
		'name': 'kitchen sink',
		'synonyms': '',
	}, {
		'code': 'f213',
		'class': 'dashicons-editor-underline',
		'name': 'underline',
		'synonyms': '',
	}, {
		'code': 'f214',
		'class': 'dashicons-editor-justify',
		'name': 'justify',
		'synonyms': '',
	}, {
		'code': 'f215',
		'class': 'dashicons-editor-textcolor',
		'name': 'textcolor',
		'synonyms': '',
	}, {
		'code': 'f216',
		'class': 'dashicons-editor-paste-word',
		'name': 'paste',
		'synonyms': '',
	}, {
		'code': 'f217',
		'class': 'dashicons-editor-paste-text',
		'name': 'paste',
		'synonyms': '',
	}, {
		'code': 'f218',
		'class': 'dashicons-editor-removeformatting',
		'name': 'remove formatting',
		'synonyms': '',
	}, {
		'code': 'f219',
		'class': 'dashicons-editor-video',
		'name': 'video',
		'synonyms': '',
	}, {
		'code': 'f220',
		'class': 'dashicons-editor-customchar',
		'name': 'custom character',
		'synonyms': '',
	}, {
		'code': 'f221',
		'class': 'dashicons-editor-outdent',
		'name': 'outdent',
		'synonyms': '',
	}, {
		'code': 'f222',
		'class': 'dashicons-editor-indent',
		'name': 'indent',
		'synonyms': '',
	}, {
		'code': 'f223',
		'class': 'dashicons-editor-help',
		'name': 'help',
		'synonyms': '',
	}, {
		'code': 'f224',
		'class': 'dashicons-editor-strikethrough',
		'name': 'strikethrough',
		'synonyms': '',
	}, {
		'code': 'f225',
		'class': 'dashicons-editor-unlink',
		'name': 'unlink',
		'synonyms': '',
	}, {
		'code': 'f320',
		'class': 'dashicons-editor-rtl',
		'name': 'rtl',
		'synonyms': '',
	}, {
		'code': 'f474',
		'class': 'dashicons-editor-break',
		'name': 'break',
		'synonyms': '',
	}, {
		'code': 'f475',
		'class': 'dashicons-editor-code',
		'name': 'code',
		'synonyms': '',
	}, {
		'code': 'f476',
		'class': 'dashicons-editor-paragraph',
		'name': 'paragraph',
		'synonyms': '',
	}, {
		'code': 'f535',
		'class': 'dashicons-editor-table',
		'name': 'table',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Posts Screen'
	'icons': [{
		'code': 'f135',
		'class': 'dashicons-align-left',
		'name': 'align left',
		'synonyms': '',
	}, {
		'code': 'f136',
		'class': 'dashicons-align-right',
		'name': 'align right',
		'synonyms': '',
	}, {
		'code': 'f134',
		'class': 'dashicons-align-center',
		'name': 'align center',
		'synonyms': '',
	}, {
		'code': 'f138',
		'class': 'dashicons-align-none',
		'name': 'align none',
		'synonyms': '',
	}, {
		'code': 'f160',
		'class': 'dashicons-lock',
		'name': 'lock',
		'synonyms': '',
	}, {
		'code': 'f528',
		'class': 'dashicons-unlock',
		'name': 'unlock',
		'synonyms': '',
	}, {
		'code': 'f145',
		'class': 'dashicons-calendar',
		'name': 'calendar',
		'synonyms': '',
	}, {
		'code': 'f508',
		'class': 'dashicons-calendar-alt',
		'name': 'calendar',
		'synonyms': '',
	}, {
		'code': 'f177',
		'class': 'dashicons-visibility',
		'name': 'visibility',
		'synonyms': '',
	}, {
		'code': 'f530',
		'class': 'dashicons-hidden',
		'name': 'hidden',
		'synonyms': '',
	}, {
		'code': 'f173',
		'class': 'dashicons-post-status',
		'name': 'post status',
		'synonyms': '',
	}, {
		'code': 'f464',
		'class': 'dashicons-edit',
		'name': 'edit pencil',
		'synonyms': '',
	}, {
		'code': 'f182',
		'class': 'dashicons-trash',
		'name': 'trash remove delete',
		'synonyms': '',
	}, {
		'code': 'f537',
		'class': 'dashicons-sticky',
		'name': 'sticky',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Sorting'
	'icons': [{
		'code': 'f504',
		'class': 'dashicons-external',
		'name': 'external',
		'synonyms': '',
	}, {
		'code': 'f142',
		'class': 'dashicons-arrow-up',
		'name': 'arrow-up',
		'synonyms': '',
	}, {
		'code': 'f140',
		'class': 'dashicons-arrow-down',
		'name': 'arrow-down',
		'synonyms': '',
	}, {
		'code': 'f139',
		'class': 'dashicons-arrow-right',
		'name': 'arrow-right',
		'synonyms': '',
	}, {
		'code': 'f141',
		'class': 'dashicons-arrow-left',
		'name': 'arrow-left',
		'synonyms': '',
	}, {
		'code': 'f342',
		'class': 'dashicons-arrow-up-alt',
		'name': 'arrow-up',
		'synonyms': '',
	}, {
		'code': 'f346',
		'class': 'dashicons-arrow-down-alt',
		'name': 'arrow-down',
		'synonyms': '',
	}, {
		'code': 'f344',
		'class': 'dashicons-arrow-right-alt',
		'name': 'arrow-right',
		'synonyms': '',
	}, {
		'code': 'f340',
		'class': 'dashicons-arrow-left-alt',
		'name': 'arrow-left',
		'synonyms': '',
	}, {
		'code': 'f343',
		'class': 'dashicons-arrow-up-alt2',
		'name': 'arrow-up',
		'synonyms': '',
	}, {
		'code': 'f347',
		'class': 'dashicons-arrow-down-alt2',
		'name': 'arrow-down',
		'synonyms': '',
	}, {
		'code': 'f345',
		'class': 'dashicons-arrow-right-alt2',
		'name': 'arrow-right',
		'synonyms': '',
	}, {
		'code': 'f341',
		'class': 'dashicons-arrow-left-alt2',
		'name': 'arrow-left',
		'synonyms': '',
	}, {
		'code': 'f156',
		'class': 'dashicons-sort',
		'name': 'sort',
		'synonyms': '',
	}, {
		'code': 'f229',
		'class': 'dashicons-leftright',
		'name': 'left right',
		'synonyms': '',
	}, {
		'code': 'f503',
		'class': 'dashicons-randomize',
		'name': 'randomize shuffle',
		'synonyms': '',
	}, {
		'code': 'f163',
		'class': 'dashicons-list-view',
		'name': 'list view',
		'synonyms': '',
	}, {
		'code': 'f164',
		'class': 'dashicons-exerpt-view',
		'name': 'exerpt view',
		'synonyms': '',
	}, {
		'code': 'f509',
		'class': 'dashicons-grid-view',
		'name': 'grid view',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Social'
	'icons': [{
		'code': 'f237',
		'class': 'dashicons-share',
		'name': 'share',
		'synonyms': '',
	}, {
		'code': 'f240',
		'class': 'dashicons-share-alt',
		'name': 'share',
		'synonyms': '',
	}, {
		'code': 'f242',
		'class': 'dashicons-share-alt2',
		'name': 'share',
		'synonyms': '',
	}, {
		'code': 'f301',
		'class': 'dashicons-twitter',
		'name': 'twitter social',
		'synonyms': '',
	}, {
		'code': 'f303',
		'class': 'dashicons-rss',
		'name': 'rss',
		'synonyms': '',
	}, {
		'code': 'f465',
		'class': 'dashicons-email',
		'name': 'email',
		'synonyms': '',
	}, {
		'code': 'f466',
		'class': 'dashicons-email-alt',
		'name': 'email',
		'synonyms': '',
	}, {
		'code': 'f304',
		'class': 'dashicons-facebook',
		'name': 'facebook social',
		'synonyms': '',
	}, {
		'code': 'f305',
		'class': 'dashicons-facebook-alt',
		'name': 'facebook social',
		'synonyms': '',
	}, {
		'code': 'f462',
		'class': 'dashicons-googleplus',
		'name': 'googleplus social',
		'synonyms': '',
	}, {
		'code': 'f325',
		'class': 'dashicons-networking',
		'name': 'networking social',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'WordPress.org Specific: Jobs, Profiles, WordCamps'
	'icons': [{
		'code': 'f308',
		'class': 'dashicons-hammer',
		'name': 'hammer development',
		'synonyms': '',
	}, {
		'code': 'f309',
		'class': 'dashicons-art',
		'name': 'art design',
		'synonyms': '',
	}, {
		'code': 'f310',
		'class': 'dashicons-migrate',
		'name': 'migrate migration',
		'synonyms': '',
	}, {
		'code': 'f311',
		'class': 'dashicons-performance',
		'name': 'performance',
		'synonyms': '',
	}, {
		'code': 'f483',
		'class': 'dashicons-universal-access',
		'name': 'universal access accessibility',
		'synonyms': '',
	}, {
		'code': 'f507',
		'class': 'dashicons-universal-access-alt',
		'name': 'universal access accessibility',
		'synonyms': '',
	}, {
		'code': 'f486',
		'class': 'dashicons-tickets',
		'name': 'tickets',
		'synonyms': '',
	}, {
		'code': 'f484',
		'class': 'dashicons-nametag',
		'name': 'nametag',
		'synonyms': '',
	}, {
		'code': 'f481',
		'class': 'dashicons-clipboard',
		'name': 'clipboard',
		'synonyms': '',
	}, {
		'code': 'f487',
		'class': 'dashicons-heart',
		'name': 'heart',
		'synonyms': '',
	}, {
		'code': 'f488',
		'class': 'dashicons-megaphone',
		'name': 'megaphone',
		'synonyms': '',
	}, {
		'code': 'f489',
		'class': 'dashicons-schedule',
		'name': 'schedule',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Products'
	'icons': [{
		'code': 'f120',
		'class': 'dashicons-wordpress',
		'name': 'wordpress',
		'synonyms': '',
	}, {
		'code': 'f324',
		'class': 'dashicons-wordpress-alt',
		'name': 'wordpress',
		'synonyms': '',
	}, {
		'code': 'f157',
		'class': 'dashicons-pressthis',
		'name': 'press this',
		'synonyms': '',
	}, {
		'code': 'f463',
		'class': 'dashicons-update',
		'name': 'update',
		'synonyms': '',
	}, {
		'code': 'f180',
		'class': 'dashicons-screenoptions',
		'name': 'screenoptions',
		'synonyms': '',
	}, {
		'code': 'f348',
		'class': 'dashicons-info',
		'name': 'info',
		'synonyms': '',
	}, {
		'code': 'f174',
		'class': 'dashicons-cart',
		'name': 'cart shopping',
		'synonyms': '',
	}, {
		'code': 'f175',
		'class': 'dashicons-feedback',
		'name': 'feedback form',
		'synonyms': '',
	}, {
		'code': 'f176',
		'class': 'dashicons-cloud',
		'name': 'cloud',
		'synonyms': '',
	}, {
		'code': 'f326',
		'class': 'dashicons-translation',
		'name': 'translation language',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Taxonomies'
	'icons': [{
		'code': 'f323',
		'class': 'dashicons-tag',
		'name': 'tag',
		'synonyms': '',
	}, {
		'code': 'f318',
		'class': 'dashicons-category',
		'name': 'category',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Widgets'
	'icons': [{
		'code': 'f480',
		'class': 'dashicons-archive',
		'name': 'archive',
		'synonyms': '',
	}, {
		'code': 'f479',
		'class': 'dashicons-tagcloud',
		'name': 'tagcloud',
		'synonyms': '',
	}, {
		'code': 'f478',
		'class': 'dashicons-text',
		'name': 'text',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Notifications'
	'icons': [{
		'code': 'f147',
		'class': 'dashicons-yes',
		'name': 'yes check checkmark',
		'synonyms': '',
	}, {
		'code': 'f158',
		'class': 'dashicons-no',
		'name': 'no x',
		'synonyms': '',
	}, {
		'code': 'f335',
		'class': 'dashicons-no-alt',
		'name': 'no x',
		'synonyms': '',
	}, {
		'code': 'f132',
		'class': 'dashicons-plus',
		'name': 'plus add increase',
		'synonyms': '',
	}, {
		'code': 'f502',
		'class': 'dashicons-plus-alt',
		'name': 'plus add increase',
		'synonyms': '',
	}, {
		'code': 'f460',
		'class': 'dashicons-minus',
		'name': 'minus decrease',
		'synonyms': '',
	}, {
		'code': 'f153',
		'class': 'dashicons-dismiss',
		'name': 'dismiss',
		'synonyms': '',
	}, {
		'code': 'f159',
		'class': 'dashicons-marker',
		'name': 'marker',
		'synonyms': '',
	}, {
		'code': 'f155',
		'class': 'dashicons-star-filled',
		'name': 'filled star',
		'synonyms': '',
	}, {
		'code': 'f459',
		'class': 'dashicons-star-half',
		'name': 'half star',
		'synonyms': '',
	}, {
		'code': 'f154',
		'class': 'dashicons-star-empty',
		'name': 'empty star',
		'synonyms': '',
	}, {
		'code': 'f227',
		'class': 'dashicons-flag',
		'name': 'flag',
		'synonyms': '',
	}, {
		'code': 'f534',
		'class': 'dashicons-warning',
		'name': 'warning',
		'synonyms': '',
	}, {
		}]
}, {
	'name': 'Misc'
	'icons': [{
		'code': 'f230',
		'class': 'dashicons-location',
		'name': 'location pin',
		'synonyms': '',
	}, {
		'code': 'f231',
		'class': 'dashicons-location-alt',
		'name': 'location',
		'synonyms': '',
	}, {
		'code': 'f178',
		'class': 'dashicons-vault',
		'name': 'vault safe',
		'synonyms': '',
	}, {
		'code': 'f332',
		'class': 'dashicons-shield',
		'name': 'shield',
		'synonyms': '',
	}, {
		'code': 'f334',
		'class': 'dashicons-shield-alt',
		'name': 'shield',
		'synonyms': '',
	}, {
		'code': 'f468',
		'class': 'dashicons-sos',
		'name': 'sos help',
		'synonyms': '',
	}, {
		'code': 'f179',
		'class': 'dashicons-search',
		'name': 'search',
		'synonyms': '',
	}, {
		'code': 'f181',
		'class': 'dashicons-slides',
		'name': 'slides',
		'synonyms': '',
	}, {
		'code': 'f183',
		'class': 'dashicons-analytics',
		'name': 'analytics',
		'synonyms': '',
	}, {
		'code': 'f184',
		'class': 'dashicons-chart-pie',
		'name': 'pie chart',
		'synonyms': '',
	}, {
		'code': 'f185',
		'class': 'dashicons-chart-bar',
		'name': 'bar chart',
		'synonyms': '',
	}, {
		'code': 'f238',
		'class': 'dashicons-chart-line',
		'name': 'line chart',
		'synonyms': '',
	}, {
		'code': 'f239',
		'class': 'dashicons-chart-area',
		'name': 'area chart',
		'synonyms': '',
	}, {
		'code': 'f307',
		'class': 'dashicons-groups',
		'name': 'groups',
		'synonyms': '',
	}, {
		'code': 'f338',
		'class': 'dashicons-businessman',
		'name': 'businessman',
		'synonyms': '',
	}, {
		'code': 'f336',
		'class': 'dashicons-id',
		'name': 'id',
		'synonyms': '',
	}, {
		'code': 'f337',
		'class': 'dashicons-id-alt',
		'name': 'id',
		'synonyms': '',
	}, {
		'code': 'f312',
		'class': 'dashicons-products',
		'name': 'products',
		'synonyms': '',
	}, {
		'code': 'f313',
		'class': 'dashicons-awards',
		'name': 'awards',
		'synonyms': '',
	}, {
		'code': 'f314',
		'class': 'dashicons-forms',
		'name': 'forms',
		'synonyms': '',
	}, {
		'code': 'f473',
		'class': 'dashicons-testimonial',
		'name': 'testimonial',
		'synonyms': '',
	}, {
		'code': 'f322',
		'class': 'dashicons-portfolio',
		'name': 'portfolio',
		'synonyms': '',
	}, {
		'code': 'f330',
		'class': 'dashicons-book',
		'name': 'book',
		'synonyms': '',
	}, {
		'code': 'f331',
		'class': 'dashicons-book-alt',
		'name': 'book',
		'synonyms': '',
	}, {
		'code': 'f316',
		'class': 'dashicons-download',
		'name': 'download',
		'synonyms': '',
	}, {
		'code': 'f317',
		'class': 'dashicons-upload',
		'name': 'upload',
		'synonyms': '',
	}, {
		'code': 'f321',
		'class': 'dashicons-backup',
		'name': 'backup',
		'synonyms': '',
	}, {
		'code': 'f469',
		'class': 'dashicons-clock',
		'name': 'clock',
		'synonyms': '',
	}, {
		'code': 'f339',
		'class': 'dashicons-lightbulb',
		'name': 'lightbulb',
		'synonyms': '',
	}, {
		'code': 'f482',
		'class': 'dashicons-microphone',
		'name': 'microphone mic',
		'synonyms': '',
	}, {
		'code': 'f472',
		'class': 'dashicons-desktop',
		'name': 'desktop monitor',
		'synonyms': '',
	}, {
		'code': 'f471',
		'class': 'dashicons-tablet',
		'name': 'tablet ipad',
		'synonyms': '',
	}, {
		'code': 'f470',
		'class': 'dashicons-smartphone',
		'name': 'smartphone iphone',
		'synonyms': '',
	}, {
		'code': 'f525',
		'class': 'dashicons-phone',
		'name': 'phone',
		'synonyms': '',
	}, {
		'code': 'f510',
		'class': 'dashicons-index-card',
		'name': 'index card',
		'synonyms': '',
	}, {
		'code': 'f511',
		'class': 'dashicons-carrot',
		'name': 'carrot food vendor',
		'synonyms': '',
	}, {
		'code': 'f512',
		'class': 'dashicons-building',
		'name': 'building',
		'synonyms': '',
	}, {
		'code': 'f513',
		'class': 'dashicons-store',
		'name': 'store',
		'synonyms': '',
	}, {
		'code': 'f514',
		'class': 'dashicons-album',
		'name': 'album',
		'synonyms': '',
	}, {
		'code': 'f527',
		'class': 'dashicons-palmtree',
		'name': 'palm tree',
		'synonyms': '',
	}, {
		'code': 'f524',
		'class': 'dashicons-tickets-alt',
		'name': 'tickets (alt)',
		'synonyms': '',
	}, {
		'code': 'f526',
		'class': 'dashicons-money',
		'name': 'money',
		'synonyms': '',
	}, {
		'code': 'f328',
		'class': 'dashicons-smiley',
		'name': 'smiley smile',
		'synonyms': '',
	}, {
		'code': 'f529',
		'class': 'dashicons-thumbs-up',
		'name': 'thumbs up',
		'synonyms': '',
	}, {
		'code': 'f542',
		'class': 'dashicons-thumbs-down',
		'name': 'thumbs down',
		'synonyms': '',
	}, {
		'code': 'f538',
		'class': 'dashicons-layout',
		'name': 'layout',
		'synonyms': '',
	}
}]
